#!/bin/bash


CLAS12OFFLINE=/usr/clas12/offline
CLAS12DIR=$CLAS12OFFLINE/coatjava/pro; export CLAS12DIR

if [ $# -lt 1 ]; then
   $CLAS12OFFLINE/clas12mon/pro/bin/mon12 -tabs "BAND:BMT:BST:CND:CTOF:DC:ECAL:FMT:FTOF:HTCC:RICH:RF:HEL:Trigger:TimeJitter" -trigger 0x1
else
   $CLAS12OFFLINE/clas12mon/pro/bin/mon12 $*
fi

