#!/bin/bash


CLAS12OFFLINE=/usr/clas12/offline
CLAS12DIR=$CLAS12OFFLINE/coatjava/pro; export CLAS12DIR

if [ $# -lt 1 ]; then
   $CLAS12OFFLINE/clas12mon/pro/bin/mon12 -tabs "BMT:BST:CND:CTOF:DC:ECAL:FTCAL:FTHODO:FTOF:FTTRK:HTCC:LTCC:RICH:RF:HEL:TimeJitter" -trigger 0x1
else
   $CLAS12OFFLINE/clas12mon/pro/bin/mon12 $*
fi

