#!/bin/bash


CLAS12OFFLINE=/usr/clas12/offline
CLAS12DIR=$CLAS12OFFLINE/coatjava/pro; export CLAS12DIR

if [ $# -lt 1 ]; then
   $CLAS12OFFLINE/clas12mon/pro/bin/mon12 -tabs "FTOF:RF:TDC:Trigger:TimeJitter"
else
   $CLAS12OFFLINE/clas12mon/pro/bin/mon12 $*
fi

